### ISSUE TITLE
Client freeze latest log report

### ISSUE THREAD

**Issue by Azuraprincess** [kreezxil/World-of-Dragons-A-New-Age#26]
[latest.log](https://github.com/kreezxil/World-of-Dragons-A-New-Age/files/3814732/latest.log)

**Comment by Azuraprincess** [comment]
[latest.log](https://github.com/kreezxil/World-of-Dragons-A-New-Age/files/3814859/latest.log)

**Comment by Azuraprincess** [comment]
ok so now im having a different thing causing a freeze on me but it doesnt list any mods

**Comment by Azuraprincess** [comment]
[latest.log](https://github.com/kreezxil/World-of-Dragons-A-New-Age/files/3816732/latest.log)

**Comment by Azuraprincess** [comment]
tried logging back in and now i have a crash report to go along with this

**Comment by Azuraprincess** [comment]
[crash-2019-11-06_16.12.18-client.txt](https://github.com/kreezxil/World-of-Dragons-A-New-Age/files/3816748/crash-2019-11-06_16.12.18-client.txt)

**Comment by CriswellCodes** [comment]
rewriting this using ubuntu for easier access

**Comment by kreezxil** [comment]
@Azuraprincess let me get you to save some steps now that you are starting to get used to this. when posting a file. 

1. open the file and
1. hit the edit menu and 
1. then hit select all,
1.  then edit again and 
1. then copy, 
1. then goto https://paste.ubuntu.com and 
1. in the large box, click in it and 
1. then on your keyboard hit CTRL then V on Apple that would be Option + V, 
1. then  hit the submit button, 
1. the page will change and but will look the same, 
1. there will be a new url/address at the top. 
1. copy that url, and 
1. then paste in the issues here.

This seems alot but it will become second nature really fast it saves those trying to help from actually having to download the file then open it, it'll just open right in their browsers.

**Comment by CriswellCodes** [comment]
Found to be a forge issue. Closing topic at this time.

Quote from discord related to closing:
"KreezxilToday at 2:33 PM
today i'm working on finding out which of the older forges i can roll down to that doesn't break the mods. because forge is what is causing the random crashes/freezes

TarlinToday at 2:33 PM
Ok, so can I close the latest.logs posts from azureprincess?

KreezxilToday at 2:33 PM
once we have that, we'll hold on w/e that forge is, I'll keep trying newer forges, however, we'll test them on the prebuild server for a few hours before we either take it or go back to the older one i'm working on finding
yes, i've asked her stop for now
NEW MESSAGES

KreezxilToday at 2:34 PM
you can ask everyone reporting random freezes in any 1.14.4 pack to stop with the reports, it's forge related"
