### ISSUE TITLE
Random Freezing

### ISSUE THREAD

**Issue by SourMelion** [kreezxil/World-of-Dragons-A-New-Age#29]
[latest.log](https://github.com/kreezxil/World-of-Dragons-A-New-Age/files/3816956/latest.log)

**Comment by kreezxil** [comment]
@SourMelion let me get you to save some steps now that you are starting to get used to this. when posting a file.

1. open the file and 
1. hit the edit menu and 
1. then hit select all,
1. then edit again and 
1. then copy, 
1. then goto https://paste.ubuntu.com and 
1. in the large box, click in it and 
1. then on your keyboard hit CTRL then V on Apple that would be Option  V, 
1. then  hit the submit button, 
1. the page will change and but will look the same, 
1. there will be a new url/address at the top. 
1. copy that url, and 
1. then paste in the issues here.


This seems alot but it will become second nature really fast it saves those trying to help from actually having to download the file then open it, it'll just open right in their browsers.

**Comment by kreezxil** [comment]
@SourMelion looking at your report, nothing seems out of the oridinary.

HOWEVER

I'm willing to bet you ran out of assigned memory to the pack.

Please adjust the packs ram to 3.5GB if you only have 4GB total system and 5 to 6GB if you have more than that. I think you will find that it works.

**Comment by kreezxil** [comment]
this is definitely related to forge, we're going down to forge build 79, we won't be going up until there is one that doesn't cause random freezes, as such there will be long stretches where mods won't update because they will be requiring forge versions that freeze the client.

I'm closing this for now. open it again after today's build 1.12.13 is out and freezes begin to happen again, remember to include latest.logs

btw, we've determined that the first 100 lines and the last 500 lines will be sufficient from the latest.logs, that should solve the file too big issue with pastebins.
