### ISSUE TITLE
Server Crash

### ISSUE THREAD

**Issue by xxkainexx** [kreezxil/World-of-Dragons-A-New-Age#46]
Picking up an upgraded dog from doggy talents will cause the server to crash.
 To replicate tame a wolf level up the dog with treats and put points in the dog mount and shift right click on the dog and will crash the server.

**Comment by xxkainexx** [comment]
doesn't have to be upgraded

**Comment by kreezxil** [comment]
I'll report this to doggy talents, wish you had done it tho because then you could've told it from your point of view, and then you cross link to here.

Our only recourse is to remove doggy talents.

https://github.com/percivalalb/DoggyTalents/issues/205

this mod will be removed from the pack. we will add it back when and if the mod author fixes the issue. I'll leave this report open as a reminder.
