### ISSUE TITLE
Mod Suggestion Good Night's Sleep mod

### ISSUE THREAD

**Issue by Azuraprincess** [kreezxil/World-of-Dragons-A-New-Age#62]
https://www.curseforge.com/minecraft/mc-mods/good-nights-sleep
For those who sleep at night it would be interesting because its a dimension mod revolving around sleep and might actually get people who dont sleep to actually sleep XD

**Comment by CriswellCodes** [comment]
This really does seem interesting, but I wonder how long you would be in this world or if it would cause issues with the current sleep mod that we have that sets it from night to day. I know that a lot of players only sleep in order for it to be daytime again. Would this also conflict with minecolonies workers in any way?

**Comment by kreezxil** [comment]
added.

- apparently there are 2 beds,
    - one enters the good night
    - the other enters the nightmare
- not entirely sure if the sleep mod prevents those beds from being used
- do know that normal beds can't enter either dimension
- did configure it so that good night is noon all the time
- and that nightmare is always midnite
- that was recommended for servers.

**this mod** will ultimately decide if we can disable morpheus. I'm all in favor of that because not fighting night mobs is a true tactical issue that ends up avoiding parts of other mods that can be used to defend against night mobs.
