### ISSUE TITLE
Request for some mods

### ISSUE THREAD

**Issue by xxkainexx** [kreezxil/World-of-Dragons-A-New-Age#8]
Corail tombstone mod
  Having a tombstone could save a lot of people from raging because they lost their stuff to lava or hordes.

https://www.curseforge.com/minecraft/mc-mods/corail-tombstone

Plant tech 2
  Why not have science based agriculture.

https://www.curseforge.com/minecraft/mc-mods/planttech-2

Bluepower
  Well we dont have much in the way of redstone control could be nice have.

https://www.curseforge.com/minecraft/mc-mods/blue-power

**Comment by kreezxil** [comment]
I will never have a tombstone/grave mod part of my pack ever. I spend about
9 months 2 years ago troubleshooting why everyone was saying the pack was
too easy despite the strength of the mobs and the types of mobs being
added. Turns out the gravestone mods make everyone play like they're a god.

So ABSOLUTELY NOT TO GRAVES. You are however have my permission to fork the
pack, add it, and republish it as your own creation. However, support and
updates will fall on you.

The other two mods if they are FORGE, i will add them. if they are not, i
will not. I only do FORGE.

**Comment by kreezxil** [comment]
ok, i've decided to tombstone, but in butthead mode. it will lose 30% of your stuff, and spawn mobs on top. if it won't let me do that, I'll not include it.

The other mods have been added.

provided they don't crash my test server, they'll be the release build later tonite.
