### ISSUE TITLE
minecolony boundary issue

### ISSUE THREAD

**Issue by Azuraprincess** [kreezxil/World-of-Dragons-A-New-Age#92]
so i logged in after awhile of not being on when i noticed that someone else has attached a colony boundary to the edges of my boundary ill show a picture of both boundaries in next post.

**Comment by Azuraprincess** [comment]
![2019-12-09_15 36 05](https://user-images.githubusercontent.com/50385859/70473109-6206f700-1a9e-11ea-8f3e-d4098b96f4d6.png)
Azureprincess boundary.

**Comment by Azuraprincess** [comment]
![2019-12-09_15 36 10](https://user-images.githubusercontent.com/50385859/70473141-72b76d00-1a9e-11ea-86bd-ee95642db00e.png)
Brasilian42's boundary

**Comment by Azuraprincess** [comment]
Kobii Fixed the issue somehow managed to remove the boundary that wasnt suppose to be there

**Comment by kreezxil** [comment]
Turns out this is an actual issue with Minecraft that existed since day one.

Randomly and know one knew why until 1.15 a chunk would either forget
itself or transpose itself to other chunks elsewhere in the world.

I've been told that this has been fixed in Minecraft 1.15, so whenever
FORGE gets there, then this will be truly fixed.
